FROM flink:1.17.2

USER root
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev curl && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# Download the Kafka Connector
RUN curl https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.0.1-1.17/flink-sql-connector-kafka-3.0.1-1.17.jar \
    -o /opt/flink/lib/flink-sql-connector-kafka-3.0.1-1.17.jar

RUN pip3 install apache-flink==1.17.2 boto3

USER flink